<?php

declare(strict_types=1);

namespace DigitalAnomaly\AlteredLogic\Support\Http\Traits;

use CodeDistortion\Backoff\Backoff;
use DigitalAnomaly\AlteredLogic\Interfaces\Http\HttpPendingRequestInterface;
use DigitalAnomaly\AlteredLogic\Interfaces\Http\HttpStreamInterface;
use DigitalAnomaly\AlteredLogic\Support\Http\DTOs\HttpTxnDTO;
use DigitalAnomaly\AlteredLogic\Support\Settings;

/**
 * A trait for HTTP clients that have HTTP settings.
 *
 * @see HttpPendingRequestInterface
 */
trait HasCommonHttpTrait
{
    /** @var array<string,string> The headers to send with the request. */
    private array $headers = [];

    /** @var array{0:string,1:string}|null The basic authentication credentials to send with the request. */
    private ?array $basicAuth = null;

    /** @var string|null The bearer token to send with the request. */
    private ?string $bearerToken = null;

    /** @var integer|float The timeout when establishing a connection. */
    private int|float $connectionTimeoutSeconds = 3;

    /** @var integer|float The timeout when receiving data. */
    private int|float $receiveTimeoutSeconds = 120;

    /** @var Backoff|null The backoff strategy to use. */
    private ?Backoff $backoff = null;



    /** @var HttpTxnDTO|null The transmission summary, generated by sending the request. */
    private ?HttpTxnDTO $httpTxn = null;





    /**
     * Add a header to the request.
     *
     * @param string $key   The key of the header.
     * @param string $value The value of the header.
     * @return self
     */
    public function withHeader(string $key, string $value): HttpPendingRequestInterface
    {
        $this->withHeaders([$key => $value]);

        return $this;
    }

    /**
     * Add multiple headers to the request.
     *
     * @param array<string,string> $headers The headers to add.
     * @return self
     */
    public function withHeaders(array $headers): HttpPendingRequestInterface
    {
        $this->headers = \array_merge_recursive($this->headers, $headers);

        return $this;
    }

    /**
     * Get the headers.
     *
     * @return array<string,string>
     */
    private function getHeaders(): array
    {
        return $this->headers;
    }

    /**
     * Build the user agent.
     *
     * @param string $httpClientName    The name of the HTTP client.
     * @param string $httpClientVersion The version of the HTTP client.
     * @return string
     */
    private function buildUserAgent(string $httpClientName, string $httpClientVersion): string
    {
        $alteredLogic = Settings::VERSION;
        $phpVersion = \phpversion();
        return "alteredLogic ({$alteredLogic}) / {$httpClientName} ({$httpClientVersion}) / PHP ({$phpVersion})";
    }





    /**
     * Add basic authentication to the request.
     *
     * @param string $username The username.
     * @param string $password The password.
     * @return self
     */
    public function withBasicAuth(string $username, string $password): HttpPendingRequestInterface
    {
        $this->basicAuth = [$username, $password];

        return $this;
    }

    /**
     * Get the basic authentication credentials.
     *
     * @return array{0:string,1:string}|null
     */
    private function getBasicAuth(): ?array
    {
        return $this->basicAuth;
    }

    /**
     * Add a bearer token to the request.
     *
     * @param string $token The token.
     * @return self
     */
    public function withBearerToken(string $token): HttpPendingRequestInterface
    {
        $this->bearerToken = $token;

        return $this;
    }

    /**
     * Get the bearer token.
     *
     * @return string|null
     */
    private function getBearerToken(): ?string
    {
        return $this->bearerToken;
    }

    /**
     * Mask the Authorization header so it isn't logged.
     *
     * @param array<string,string[]> $headers The headers to update.
     * @return array<string,string[]>
     */
    private function maskAuthHeaders(array $headers): array
    {
        foreach (\array_keys($headers) as $key) {

            if (\mb_strtolower($key) !== 'authorization') {
                continue;
            }

            // replace "<method> <token>" with "<method> (removed)"
            // e.g. "Bearer dGF5bG9yQGxhcmF2ZWwuY29tOnNlY3JldA==" with "Bearer (removed)"
            // e.g. "Basic dGF5bG9yQGxhcmF2ZWwuY29tOnNlY3JldA==" with "Basic (removed)"
            foreach ($headers[$key] ?? [] as $index => $value) {
                \preg_match('/^([^\s]+)\s+/', $value, $matches);
                if (\array_key_exists(1, $matches)) {
                    $headers[$key][$index] = "{$matches[1]} (removed)";
                }
            }
        }

        return $headers;
    }





    /**
     * Set the connection timeout.
     *
     * @param integer|float $seconds The timeout in seconds.
     * @return self
     */
    public function withConnectTimeout(int|float $seconds): HttpPendingRequestInterface
    {
        $this->connectionTimeoutSeconds = $seconds;

        return $this;
    }

    /**
     * Get the connection timeout.
     *
     * @return integer|float
     */
    private function getConnectionTimeout(): int|float
    {
        return $this->connectionTimeoutSeconds;
    }

    /**
     * Set the receive timeout.
     *
     * @param integer|float $seconds The timeout in seconds.
     * @return self
     */
    public function withReceiveTimeout(int|float $seconds): HttpPendingRequestInterface
    {
        $this->receiveTimeoutSeconds = $seconds;

        return $this;
    }

    /**
     * Get the receive timeout.
     *
     * @return integer|float
     */
    private function getReceiveTimeout(): int|float
    {
        return $this->receiveTimeoutSeconds;
    }





    /**
     * Specify the backoff strategy to use.
     *
     * @param Backoff|null $backoff The backoff strategy to use.
     * @return self
     */
    public function withBackoff(?Backoff $backoff): HttpPendingRequestInterface
    {
        $this->backoff = $backoff;

        return $this;
    }

    /**
     * Get the backoff strategy.
     *
     * @return Backoff|null
     */
    private function getBackoff(): ?Backoff
    {
        return $this->backoff;
    }





    /**
     * Send a GET request.
     *
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The GET parameters to send with the request.
     * @return HttpTxnDTO
     */
    public function get(string $url, array $params = []): HttpTxnDTO
    {
        return $this->_send('GET', $url, $params);
    }

    /**
     * Send a POST request.
     *
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The POST parameters to send with the request.
     * @return HttpTxnDTO
     */
    public function post(string $url, array $params = []): HttpTxnDTO
    {
        return $this->_send('POST', $url, $params);
    }

    /**
     * Send a request.
     *
     * @param string              $method The HTTP method to send the request with.
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The GET parameters to send with the request.
     * @return HttpTxnDTO
     */
    private function _send(string $method, string $url, array $params = []): HttpTxnDTO
    {
        if ($this->getBackoff() === null) {
            return $this->send($method, $url, $params);
        }

        $shouldRetryCallback = fn(HttpTxnDTO $httpTxn): bool
            => $httpTxn->response === null || $httpTxn->response->shouldRetry();

        return clone($this->getBackoff())
            ->reset()
            ->retryAllExceptions()
            ->retryWhen($shouldRetryCallback)
            ->attempt(
                fn() => $this->send($method, $url, $params)
            );
    }

    /**
     * Send a request.
     *
     * @param string              $method The HTTP method to send the request with.
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The GET parameters to send with the request.
     * @return HttpTxnDTO
     */
    abstract private function send(string $method, string $url, array $params = []): HttpTxnDTO;





    /**
     * Send a GET request, and stream the response.
     *
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The GET parameters to send with the request.
     * @return HttpStreamInterface
     */
    public function streamGet(string $url, array $params = []): HttpStreamInterface
    {
        return $this->_streamSend('GET', $url, $params);
    }

    /**
     * Send a POST request, and stream the response.
     *
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The POST parameters to send with the request.
     * @return HttpStreamInterface
     */
    public function streamPost(string $url, array $params = []): HttpStreamInterface
    {
        return $this->_streamSend('POST', $url, $params);
    }

    /**
     * Send a request, and stream the response.
     *
     * @param string              $method The HTTP method to send the request with.
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The GET parameters to send with the request.
     * @return HttpStreamInterface
     */
    private function _streamSend(string $method, string $url, array $params = []): HttpStreamInterface
    {
        // todo
        // if ($this->getBackoff() === null) {
            return $this->streamSend($method, $url, $params);
        // }

        // return clone($this->getBackoff())
        // ->reset()
        // ->retryAllExceptions()
        // ->attempt(
        //     fn() => $this->send($method, $url, $params)
        // );
    }

    /**
     * Send a request, and stream the response.
     *
     * @param string              $method The HTTP method to send the request with.
     * @param string              $url    The url to send the request to.
     * @param array<string,mixed> $params The GET parameters to send with the request.
     * @return HttpStreamInterface
     */
    abstract private function streamSend(string $method, string $url, array $params = []): HttpStreamInterface;





    /**
     * Record the httpTxn.
     *
     * @param HttpTxnDTO $httpTxn The httpTxnDTO to record.
     * @return void
     */
    private function setHttpTxn(HttpTxnDTO $httpTxn): void
    {
        $this->httpTxn = $httpTxn;
    }

    /**
     * Build an HttpTxnDTO representing the current state of the client.
     *
     * This is useful when streaming responses (as the stream is what's returned originally. e.g. ->streamPost()).
     *
     * @return HttpTxnDTO|null
     */
    public function httpTxn(): ?HttpTxnDTO
    {
        return $this->httpTxn;
    }
}
